### ISSUE TITLE
Updating translation filename

### ISSUE THREAD

**Issue by delirehberi** [eresbiotech/iyzico-sylius#7]
Reported by @tugrulgencoglu in that pr. https://github.com/workouse/iyzico-sylius/pull/6#issue-717865019

Plugin translation filenames must be in singular form instead of plural form.

we need to rename files like that; `message.yml` instead of `messages.yml`

**Comment by tugrulgencoglu** [comment]
Sorry about my bad. Sadly this is not fix missing translation keys error. Plural form of domains (like ```messages```) are right way to implement translations. I couldn't found what we are missing yet but this isn't reason of this error. 
Issue can be close
